### PR TITLE
Add Homepage

### PR DESCRIPTION
**Pull request by Kalunge**

### CODE REVIEW

**Comment by mikenath223** [comment]
Hi @Kalunge,

You made a great effort in this project, but unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that will be invalidated for this reason:
-  Include linter config files.
- Update the PR description.
- Ensure GitHub checks run and checks are green.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Happy coding. Cheers!🚀🚀

If something isn't 100% clear, you can leave comments or questions in this PR thread.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, whether valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **don't count** into the code reviews limit._

**Comment by Kalunge** [comment]
Hi  Michgolden,
Thanks for your response. just a small clarification do I need to add the
linter config files to .gitignore

**Comment by mikenath223** [comment]
No. Please don't.

**Comment by Kalunge** [comment]
close

**Comment by Kalunge** [comment]
Hello have a look at this.
https://github.com/Kalunge/Microverse-/pull/2

I don't know how to get around the node version line error in the
linters.yml file

**Pull request closed without merging**
